### ISSUE TITLE
Analise de fluxogramas x desenvolvimento [ P.O ]

### ISSUE THREAD

**Issue by Adson-Gomes-Oliveira** [TableRise/tablerise-backend#321]
É necessária uma revisão detalhada dos fluxos que compreendem a entidade de campanhas para garantir que o que foi desenvolvido está compreendendo o que consta nos fluxogramas e vice-versa, também deve-se criar fluxogramas para os processos que foram desenvolvidos mas não possuem ainda um desenho.

Rotas que foram desenvolvidas até o momento:

- Recuperar dados de uma campanha [ /campaigns/{id} ]
- Criação de uma campanha [ /campaigns/create ]
- Atualização de dados de uma campanha [ /campaigns/{id}/update/ ]
- Adição/Remoção de uma imagem de mapa para as partidas de uma campanha [ /campaigns/{id}/update/match/map-image ]
- Adição/Remoção de um link do youtube para as partidas de uma campanha [ /campaigns/{id}/update/match/music ]

Também é necessário uma revisão do que foi desenvolvido quantos a banco de dados, comparando o fluxograma **campaigns_diagram** disponível no link abaixo com as models/interfaces desenvolvidas para a entidade de campaigns na lib database-management ( https://github.com/TableRise/database-management ).

Link para os fluxogramas de campanhas: https://tablerise.slite.com/app/docs/HpzFsIVLNitEwp

**Comment by isaciqo** [comment]
1) Interface Infos vs Schema infosMongooseSchema:
O campo visibility na interface é restrito a 'hidden' | 'visible', enquanto no Mongoose Schema, parece ser uma string livre.
**(não acho q seja importante para abrir uma alteração)**

2)Interface Avatar vs Schema avatarMongooseSchema:
O campo status na interface é restrito a 'alive' | 'dead' | 'viewer', mas no Mongoose Schema, parece ser uma string livre.
**(não acho q seja importante para abrir uma alteração)**

3) Diagram. **campaigns**
ageRestriction: number; não existe no diagrama
system: não existe no diagrama

4) Diagram. **player**
status: não existe no diagrama

**Comment by isaciqo** [comment]
1)Diagram. characteristics
appearence devia ser appear**a**nce

2) interface AlliesAndOrgs
symbol devia ser uma imagem e n uma string

**Comment by Adson-Gomes-Oliveira** [comment]
> 1)Diagram. characteristics appearence devia ser appear**a**nce
> 
> 2. interface AlliesAndOrgs
>    symbol devia ser uma imagem e n uma string
> 3. interface CharactersDnd5e
>    picture: devia ser uma imagem e n uma string

1 - Concordo, deve ser feita a alteração.
2 e 3 - Criar um bug no board para arrumar os tipos na lib database-management
